name: CI
on: [push]
jobs:
  test:
    name: Test, Build, Package
    strategy:
      matrix:
        java: ['8', '11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: maven

      - name: Maven Test
        run: mvn -B test -Dmaven.javadoc.skip=true --file pom.xml

      - name: Maven Build
        run: mvn -B package -DskipTests -Dmaven.javadoc.skip=true --file pom.xml

  publish:
    name: Publish Snapshot
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          server-id: hazebyte
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: 'maven'

      - name: Deploy to Maven 
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}

  generate_docs:
    name: 'Generate latest docs'
    needs: test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Generate latest docs'
        run: mvn javadoc:javadoc
      - name: 'Upload to gh-pages'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: target/site/apidocs